name: "ðŸš€ publish"

on:
    push:
        branches:
          - main

jobs:
Â  Â  release:
Â  Â  Â  Â  name: ðŸš€ publish
Â  Â  Â  Â  runs-on: ubuntu-latest
Â  Â  Â  Â  permissions:
Â  Â  Â  Â  Â  Â  contents: read
Â  Â  Â  Â  Â  Â  id-token: write 
Â  Â  Â  Â  steps:
Â  Â  Â  Â  Â  Â  - name: ðŸ“š checkout
Â  Â  Â  Â  Â  Â  Â  uses: actions/checkout@v3
Â  Â  Â  Â  Â  Â  - name: ðŸŸ¢ node
Â  Â  Â  Â  Â  Â  Â  uses: actions/setup-node@v3
Â  Â  Â  Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  Â  Â  Â  Â  node-version: 16
Â  Â  Â  Â  Â  Â  Â  Â  Â  registry-url: https://registry.npmjs.org
Â  Â  Â  Â  Â  Â  Â  Â  Â  scope: '@lejeanf'
Â  Â  Â  Â  Â  Â  - name: ðŸš€ publish
Â  Â  Â  Â  Â  Â  Â  run: npm publish --access public 
